import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Free AI CV Builder UK 2026 — MyCVBuddy | ATS-Optimised CVs in Minutes',
  description: 'MyCVBuddy is the UK\'s free AI CV builder. Upload your CV, paste any job description, and get a tailored, ATS-optimised CV in under 2 minutes. Used by 50,000+ UK job seekers. No credit card required.',
  keywords: [
    'free cv builder uk',
    'ai cv builder uk',
    'mycv',
    'mycv buddy',
    'my cv buddy',
    'mycv builder',
    'cv builder uk',
    'cv writing service uk',
    'best cv writing service uk',
    'professional cv writer uk',
    'AI CV optimization',
    'CV tailoring uk',
    'ats cv checker',
    'ats friendly cv',
    'ats optimised cv',
    'cv writing service london',
    'cv writing service manchester',
    'cv writing service birmingham',
    'cv writing service edinburgh',
    'cv writing service glasgow',
    'uk cv format 2026',
    'how to write a cv uk',
    'cv personal statement examples uk',
    'cv examples uk',
    'marketing cv examples uk',
    'cv ideas uk',
    'cv template uk',
    'free cv template uk',
    'cv vs resume uk',
    'how to tailor a cv',
    'tailor cv to job description',
    'how long should a cv be uk',
    'graduate cv uk',
    'graduate scheme cv',
    'nhs cv format',
    'career change cv uk',
    'executive cv writer uk',
    'cover letter generator uk',
    'cover letter uk',
    'interview preparation uk',
    'professional resume writing uk',
    'resume writing services uk',
    'cv writing tips uk',
    'uk job market 2026',
    'applicant tracking system uk',
    'cv checker uk',
    'fix my cv',
    'rewrite my cv',
    'cv writing guide uk',
    'cv for uk jobs',
    'uk cv builder online free',
    'best ai cv builder',
    'ai resume builder uk',
  ],
  authors: [{ name: 'My CV Buddy Team' }],
  creator: 'My CV Buddy',
  publisher: 'My CV Buddy',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL('https://www.mycvbuddy.com'),
  alternates: {
    canonical: '/',
  },
  openGraph: {
    type: 'website',
    locale: 'en_GB',
    url: 'https://www.mycvbuddy.com',
    title: 'Free AI CV Builder UK 2026 — MyCVBuddy | ATS-Optimised CVs in Minutes',
    description: 'MyCVBuddy is the UK\'s free AI CV builder. Upload your CV, paste any job description, and get a tailored, ATS-optimised CV in under 2 minutes. 50,000+ UK job seekers. No credit card required.',
    siteName: 'MyCVBuddy',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'MyCVBuddy — Free AI CV Builder for UK Job Seekers. ATS-Optimised CVs in 2 Minutes.',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Free AI CV Builder UK 2026 — MyCVBuddy | ATS-Optimised CVs in Minutes',
    description: 'MyCVBuddy is the UK\'s free AI CV builder. Upload your CV, paste any job description, and get a tailored, ATS-optimised CV in under 2 minutes. No credit card required.',
    images: ['/og-image.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return children
}
